name: Build and Deploy Code

on: 
  push:
    branches: 
      - "main"
      - "master"


jobs:
  job1:
    env:
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
      POSTGRES_DATABASE: ${{secrets.POSTGRES_DATABASE}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}

    services:
      postgres:
        image: postgres
        
        env:
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DATABASE: ${{secrets.POSTGRES_DATABASE}}_test

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    runs-on: ubuntu-latest

    steps:
      - name: Pull git repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/ --disable-warnings -q